// Generated by tools/dev/agent-contracts.mjs from shared wire contracts. Do not edit.
export declare const MAX_STATUS_TEXT_LENGTH = 320;
export declare const GRID: {
  readonly width: 64;
  readonly height: 40;
};
/** Canonical external agent contract. Keep this module independent of host packages. */
export declare const AGENT_NAME_MAX_LENGTH = 24;
export interface AgentSceneObject {
  id?: string;
  x: number;
  y: number;
  emoji: string;
  floor?: 0 | 1;
  isEntry?: boolean;
  message?: string;
  targetRoomName?: string;
  linkedRoom?: boolean;
  portalPairId?: string;
  radioConfigured?: boolean;
  conveyorEmoji?: '➡️' | '⬇️' | '⬅️' | '⬆️';
  pianoNote?: string;
  pianoSound?: string;
}
export interface AgentScene {
  blocked: number[];
  objects: AgentSceneObject[];
  floor?: 0 | 1;
  hasBasement?: boolean;
  editing?: 'everyone' | 'owner';
  gameFacts?: {
    gemsEnabled: boolean;
    gemRefundHours: number;
  };
}
/** Version 1 of the external agent gateway. No account IDs, credentials or raw scene state. */
export interface AgentPosition {
  x: number;
  y: number;
  floor: 0 | 1;
}
export interface AgentMovement {
  id: string;
  target: AgentPosition;
  status: 'moving' | 'arrived' | 'stopped' | 'blocked' | 'timed_out' | 'disconnected';
}
export interface AgentPursuit {
  id: string;
  player: string;
  mode: 'follow' | 'approach';
  status: 'moving' | 'holding' | 'arrived' | 'stopped' | 'lost' | 'blocked' | 'timed_out';
  expiresAt: number;
}
export interface AgentObservation {
  protocol: 1;
  sessionId: string;
  revision: number;
  observedAt: number;
  room: string;
  status: string;
  self:
    | (AgentPosition & {
        id: string;
        name: string;
        text: string;
      })
    | null;
  players: Array<
    AgentPosition & {
      id: string;
      name: string;
      text: string;
      textRevision: number;
      settled: boolean;
    }
  >;
  objects: Array<
    AgentPosition & {
      emoji: string;
      text?: string;
    }
  >;
  blocked: Array<{
    x: number;
    y: number;
  }>;
  movement: AgentMovement | null;
  scene?: AgentScene;
  roster?: Array<
    AgentPosition & {
      id: string;
      name: string;
      encounterKey?: string;
    }
  >;
  interacting?: boolean;
  pursuit?: AgentPursuit | null;
  appearance?: {
    kind: string;
    emoji: string;
    model: string | null;
    expression?: string;
    expressions?: string[];
  };
  limits: {
    radius: number;
    heartbeatMs: number;
    idleTimeoutMs: number;
    maxSpeechLength: number;
  };
}
